import { MetadataRoute } from 'next';
import { SITE_CONFIG } from '@/lib/seo';
import { getAllSlugs } from '@/lib/blog';
import { FORMATION_IA_ALL_SLUGS } from '@/lib/seo-formation-ia-hub-data';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = SITE_CONFIG.url;

  const blogRoutes: MetadataRoute.Sitemap = [
    { url: `${baseUrl}/blog`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.9 },
    ...getAllSlugs().map((slug) => ({
      url: `${baseUrl}/blog/${slug}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.85 as const,
    })),
  ];

  const staticRoutes: MetadataRoute.Sitemap = [
    { url: baseUrl, lastModified: new Date(), changeFrequency: 'weekly', priority: 1 },
    {
      url: `${baseUrl}/llms.txt`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    { url: `${baseUrl}/formations`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/a-propos`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    {
      url: `${baseUrl}/etudes-de-cas/ffb-csfe`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.82,
    },
    { url: `${baseUrl}/expert-ia-btp`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${baseUrl}/auteur/laure-olivie`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${baseUrl}/contact`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/prendre-rdv`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/diagnostic-ia-btp`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/checklist-ia-btp`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/checklist-prompts-btp`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.88 },
    { url: `${baseUrl}/communaute-formateurs`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/financement-constructys-formation-ia-btp`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    {
      url: `${baseUrl}/formation-ia-travaux-publics`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    { url: `${baseUrl}/financement-constructys-100-ia-btp`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.88 },
    { url: `${baseUrl}/ressources/ia-btp`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/ressources/ia-btp/10-cas-usage-concrets`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${baseUrl}/formation-ia-btp-ile-de-france`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.9 },
    {
      url: `${baseUrl}/repondre-appels-offres-ia-btp`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.88,
    },
    { url: `${baseUrl}/formations/ia-btp-paris`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.9 },
    {
      url: `${baseUrl}/formations/ia-btp-yvelines-78`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/formation-ia-btp-yvelines`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    { url: `${baseUrl}/formations/ia-btp-lyon`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/formations/ia-btp-bordeaux`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/formations/ia-btp-lille`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.9 },
    {
      url: `${baseUrl}/formations/ia-au-service-du-batiment`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    { url: `${baseUrl}/formations/ia-travaux-publics`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${baseUrl}/formations/ia-appels-offre-btp`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${baseUrl}/formations/ia-rh-btp`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${baseUrl}/formations/ia-pme-btp`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.85 },
    {
      url: `${baseUrl}/formations/sensibilisation-ia-assistants-personnalises`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: `${baseUrl}/formations/ia-architecture-claude-dpgf`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.88,
    },
    { url: `${baseUrl}/formation-ia-artisans-btp`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/formation-ia`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.92 },
    { url: `${baseUrl}/formation-ia/faq`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.88 },
    ...FORMATION_IA_ALL_SLUGS.map((slug) => ({
      url: `${baseUrl}/formation-ia/${slug}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: slug === 'btp-paris' ? (0.93 as const) : (0.86 as const),
    })),
    { url: `${baseUrl}/ia-devis-batiment`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.9 },
    {
      url: `${baseUrl}/formation-chatgpt-artisan-electricien`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.88,
    },
    {
      url: `${baseUrl}/formation-ia-electricien-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-charpentier-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-ferrailleur-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-etancheur-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-couvreur-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-vitrier-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-plombier-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-plaquiste-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-peintre-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-menuisier-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-dirigeant-pme-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-conducteur-travaux-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-charge-affaires-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-assistante-administrative-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-pisciniste-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-paysagiste-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-macon-paysagiste-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-cloturiste-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-carreleur-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-geometre-tp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-conducteur-engins-tp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-chef-chantier-tp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-canalisateur-tp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    {
      url: `${baseUrl}/formation-ia-macon-btp`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.89,
    },
    { url: `${baseUrl}/ia-conducteur-travaux`, lastModified: new Date(), changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/mentions-legales`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: `${baseUrl}/politique-confidentialite`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: `${baseUrl}/cgv`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: `${baseUrl}/reglement-interieur`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.3 },
    { url: `${baseUrl}/offres`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/annuaire-handicap`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.5 },
    { url: `${baseUrl}/install-pwa`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    ...blogRoutes,
  ];

  return staticRoutes;
}
