/**
 * Portrait narratif long — page /a-propos (GEO / E-E-A-T).
 * Faits alignés sur le reste du site (Qualiopi, OFC, chiffres, partenaires).
 */

export const A_PROPOS_NARRATIVE_PARAGRAPHS: readonly string[] = [
  `Je m’appelle Laure Olivié : je suis formatrice IA appliquée au bâtiment et fondatrice d’OFC Création d’Entreprise, organisme certifié Qualiopi basé à Guyancourt (Yvelines). Mon métier, ce n’est pas d’ajouter de la technologie pour la technologie : c’est d’aider les équipes du bâtiment et des travaux publics — professionnels du BTP, conducteurs de travaux, directions de PME — à gagner du temps sur ce qui étouffe le quotidien : devis, relances, comptes rendus, dossiers administratifs et, quand c’est pertinent, appels d’offres et mémoires techniques.`,

  `Sur le terrain, j’ai été fondatrice et conductrice de travaux chez ALIA BTP (entreprise de terrassement et revêtements extérieurs, SIRET 853 687 317 00018, Guyancourt) de 2017 à 2024 : devis, planning, interfaces entre corps d’état. Ce qui m’a marquée, ce sont les écarts entre la complexité réelle des chantiers et la pression administrative — peu de marge pour « expérimenter » si les délais et les clients sont déjà là. Quand l’IA générative a émergé, mon réflexe n’a pas été marketing : c’était opérationnel — montrer comment un prompt bien cadré peut débloquer une rédaction, structurer une pièce ou accélérer une relecture, sans remplacer le métier ni les obligations réglementaires.`,

  `En 2022, j’ai créé OFC Création d’Entreprise pour répondre à un besoin simple : des sessions courtes, exclusivement en présentiel en Île-de-France (pas de distanciel, pas de déplacement hors IDF), avec vos vrais documents (devis, mails, pièces marchés), une exigence Qualiopi pour la transparence du programme, et un financement possible via l’OPCO Constructys lorsque l’entreprise est éligible et que le dossier est monté dans les règles. Depuis 2024, j’en assure la présidence au quotidien. La certification Qualiopi (NDA 11788515078) n’est pas un label décoratif : c’est une exigence de clarté sur les contenus et les résultats — ce qui compte pour les financeurs comme pour les équipes terrain.`,

  `Côté visibilité et transmission, j’assume aussi un rôle d’instructrice sur LinkedIn Learning : deux cours en français sur l’IA appliquée au BTP et aux TPE, pour toucher des publics au-delà de l’Île-de-France. Côté institutions, les collaborations et interventions s’appuient sur des acteurs de référence — FFB (dont FFB Grand Paris), CSFE, CNAM Entreprise, Lefebvre Dalloz, CAPEB — parce que la crédibilité d’une formatrice IA pour le BTP se joue aussi dans la capacité à parler le langage des corps de métier et des fédérations.`,

  `Ma méthode est volontairement terrain : environ 70 % de pratique sur documents réels, des prompts calibrés « vocabulaire BTP », et un accompagnement après session pour éviter que l’outil ne retombe en désuétude. Je ne promets pas de chiffres magiques : je mets en scène des gains de temps réalistes — structuration, relecture, brouillons — avec validation humaine sur tout ce qui engage la responsabilité de l’entreprise (prix, sécurité, engagements contractuels).`,

  `Les chiffres que nous publions sont consolidés : 1 592 professionnels accompagnés via OFC au 17 avril 2026 et une note de satisfaction moyenne de 4,85/5 sur les questionnaires de fin de formation — pas pour « faire joli », mais parce que c’est la même métrique que nous utilisons en interne pour ajuster les contenus. Pour la suite, l’objectif reste le même : que l’IA soit un levier de clarté et de rapidité pour celles et ceux qui construisent la ville et les infrastructures — pas une couche de complexité supplémentaire. Si vous êtes une structure du BTP en Île-de-France ou une direction qui prépare un plan de formation, vous trouverez sur ce site le catalogue, le financement Constructys et des ressources pour cadrer votre projet — avec la même exigence de sincérité que sur le terrain.`,

  `— Laure Olivié`,
];
